config/routes.rb
Rails.application.routes.draw do
  get 'gallery/index'

  get 'archives/index'

  devise_for :users, skip: :registrations
  as :user do
  	get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'    
  	put 'users' => 'devise/registrations#update', :as => 'user_registration'            
  end
  
  resources :posts do
  	 resources :comments
  end
  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
       if user.admin?
         can :manage, :all
       else
         can :read, :all
       end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :image, ImageUploader
	has_many :comments
	def day
		self.created_at.strftime("%B %Y")
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
   	def author? 
	  self.role == 'author' 
	end
	
	def admin? 
	  self.role == 'admin' 
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
    	devise_parameter_sanitizer.permit(:sign_up, keys: [:role])	
    end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
  	@posts = Post.all.order('created_at DESC').group_by(&:day)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: [:show, :edit, :update, :destroy]

  
  def show
  end

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  	@post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
  end

  # POST /comments
  # POST /comments.json
  def create
     @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    redirect_to post_path(@post)
  end

  def destroy
     @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    redirect_to post_path(@post)
  end

  def update
  	@post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params)
    @comment.update(comment_params)
    redirect_to :back 
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comment
      @comment = Comment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comment_params
      params.require(:comment).permit(:person , :comment)
    end
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.paginate(:page =>params[:page], :per_page =>5)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :content, :date, :image)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def kramdown(text)
  		return sanitize Kramdown::Document.new(text).to_html
	end

	def full_title(page_title = '')
    base_title = "Karai-GLUG"
    if page_title.empty?
      base_title
    else
      page_title + " | " + base_title
    end
  end

end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
	
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/archives/index.html.erb
<% provide(:title, "Blog-Archives") %>
<%= render 'posts/nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>
<div class="post-archive">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-sm-12">
			  <h3>Blog Archives</h3>
				    <% @posts.each do |day,posts| %>
				     <ul class="archive-list">
			    		<li class="line">
                      <h4><%= "#{day}(#{posts.count})"%></h4>
  			    	  <% for post in posts %>
  				         <div class="inner-archive">
    			            <p><%= link_to post.title, post %>
    			            .<%= link_to post.created_at.strftime("%B %d %Y"), :class => "time" %></p>
  				         </div>
                      <% end %>
                        <hr class="border">
                       </li>
                   </ul>
               <% end -%>
   			</div>
		</div>
	</div>
</div>

app/views/comments/_comment.html.erb
<p>
  <strong>Person:</strong>
  <%= comment.person %>
</p>
 
<p>
  <strong>Comment:</strong>
  <%= comment.comment %>
</p>
<p>
  <%= link_to 'Delete Comment', [comment.post, comment],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
<div class="form-group">
  
    <%= f.label :person, class: 'col-sm-3 control-label' %>
    <div class="col-sm-10">
    <%= f.text_field :person, class: 'form-control' %>
  </div>
</div>

 <div class="form-group">

<p>&nbsp;</p>
    <%= f.label :comment, class: 'col-sm-3 control-label' %>

    <div class="col-sm-10">
    <%= f.text_area :comment, class: 'form-control' %>
    </div>
    </div>


<br>
<br>
<div class="actions form-group">
    <div class="col-sm-offset-1 col-sm-8">
      
        <%= f.submit :Finish, class: 'btn btn-success' %>
</div>
</div>
<p>&nbsp;</p>
<p>&nbsp;</p>
<% end %>

app/views/gallery/index.html.erb
<% provide(:title, 'Gallery') %>
<%= render 'posts/nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>
<div class="gallery" id="gallery">
  <div class="container">  
  <div class="row">
  	<div class="col-sm-12 col-xs-12">
  		 <h4>Photo Gallery</h4>
    <hr class="line" />
      <div class="images"> 
        <a href="/assets/4.jpg">
    		<%= image_tag("/assets/4.jpg") %>
    	</a>
        
    	<a href="/assets/6.jpg">
    		<%= image_tag("/assets/6.jpg") %>
    	</a>
    	<a href="/assets/7.jpg">
    		<%= image_tag("/assets/7.jpg") %>
    	</a>
    	<a href="/assets/8.jpg">
    		<%= image_tag("/assets/8.jpg") %>
    	</a>
    	<a href="/assets/back.jpg">
    		<%= image_tag("/assets/back.jpg") %>
    	</a>
    	<a href="/assets/16.jpg">
    		<%= image_tag("/assets/16.jpg") %>
    	</a>
    	<a href="/assets/12.jpg">
    		<%= image_tag("/assets/12.jpg") %>
    	</a>
    	<a href="/assets/15.jpg">
    		<%= image_tag("/assets/15.jpg") %>
    	</a>
         <a href="/assets/17.jpg">
            <%= image_tag("/assets/17.jpg") %>
        </a>
         <a href="/assets/18.jpg">
            <%= image_tag("/assets/18.jpg") %>
        </a>
         <a href="/assets/19.jpg">
            <%= image_tag("/assets/19.jpg") %>
        </a>
         <a href="/assets/20.jpg">
            <%= image_tag("/assets/20.jpg") %>
        </a>
         <a href="/assets/21.jpg">
            <%= image_tag("/assets/21.jpg") %>
        </a>
         <a href="/assets/22.jpg">
            <%= image_tag("/assets/22.jpg") %>
        </a>
         <a href="/assets/23.jpg">
            <%= image_tag("/assets/23.jpg") %>
        </a>
         <a href="/assets/24.jpg">
            <%= image_tag("/assets/24.jpg") %>
        </a>
         <a href="/assets/25.jpg">
            <%= image_tag("/assets/25.jpg") %>
        </a>
         <a href="/assets/26.jpg">
            <%= image_tag("/assets/26.jpg") %>
        </a>
         <a href="/assets/27.jpg">
            <%= image_tag("/assets/27.jpg") %>
        </a>
         <a href="/assets/28.jpg">
            <%= image_tag("/assets/28.jpg") %>
        </a>
         <a href="/assets/29.jpg">
            <%= image_tag("/assets/29.jpg") %>
        </a>
         <a href="/assets/30.jpg">
            <%= image_tag("/assets/30.jpg") %>
        </a>
         <a href="/assets/31.jpg">
            <%= image_tag("/assets/31.jpg") %>
        </a>
         <a href="/assets/32.jpg">
            <%= image_tag("/assets/32.jpg") %>
        </a>
         <a href="/assets/33.jpg">
            <%= image_tag("/assets/33.jpg") %>
        </a>
         <a href="/assets/34.jpg">
            <%= image_tag("/assets/34.jpg") %>
        </a>
 </div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %> </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="shortcut icon" href="/assets/favicon.ico" type="favicon/ico" />
   <link href="https://fonts.googleapis.com/css?family=Berkshire+Swash|Cookie|Cormorant+Garamond|Lobster+Two|Rokkitt" rel="stylesheet"> 
   <link href="https://fonts.googleapis.com/css?family=Balthazar|Scheherazade" rel="stylesheet"> 
   <link href="https://fonts.googleapis.com/css?family=Poiret+One|Questrial" rel="stylesheet"> 
   
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.min.js" type="text/javascript"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
   <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
   
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>


  </head>

   <%= javascript_include_tag 'jquery', 'data-turbolinks-track': 'reload'%>
  

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <ul class="form-group">
    <li>
      <%= form.text_field :title, id: :post_title, :placeholder => 'Title',:class=>'form-control' %>
    </li>
    <li>
      <%= form.file_field :image, id: :post_image %>
    </li>
    <li>
      <%= form.date_select :date, id: :post_date,:class=>'form-control' %>
    </li>
  </ul>   
    <%= form.text_area :content, id: :post_content,:rows => 10,:cols=>90, :placeholder => "Enter ur conent",:class=>'form-control' %>
    <br/><br/>
   <div class="actions">
    <%= form.submit "Save", :class => "submit btn btn-danger" %>
  </div>
<% end %>

app/views/posts/_nav.html.erb
   
   <nav class="navbar navbar-inverse navbar-fixed-top">
  	<div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#">MainPage</a></li>
        <li><%= link_to 'Archives', archives_index_path %></li>
        <li><a href="#">Contact-us</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <%if user_signed_in? %>
         <li><%= link_to current_user.email, '#'  %></li>
         <li> <%= link_to 'Log-Out', destroy_user_session_path, method: :delete %></li>
      <% else %>
          <li><%= link_to 'Log-in', new_user_session_path %></li>
         <% end %>
      </li>
      </ul>
    </div>
  </div>
</nav> 
   

app/views/posts/edit.html.erb
<% provide(:title, "Edit-Post") %>
<%= render 'nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>

<div class="new-post">
	<div class="container">
	  <div class="row">
	    <div class="col-sm-12 col-md-12 col-lg-9 col-sm-9">

			<h1>Editing Post</h1>

			<%= render 'form', post: @post %>

			<%= link_to 'Show', @post %> |
			<%= link_to 'Back', posts_path %>
		</div>
	  </div>
	</div>
</div>

app/views/posts/index.html.erb
<% provide(:title, "Blog") %>
<%= render 'nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>

<div class="post">
<div class="container-fluid">
  <div class="row">
   <div class=" col-sm-12 col-xs-12 col-md-9 col-lg-9">

     <p id="notice"><%= notice %></p>
     <ul class="list">
      <% @posts.each do |post| %>
      <li>
        <h5><span class="fa fa-clock-o" aria-hidden="true"></span><%= post.date.strftime("%B %d %Y") rescue nil%> </h5>
        <h3><%= post.title.capitalize %></h3>
        <p><%=  truncate(post.content, length: 200) %></p>
        <%= link_to 'Read-more', post, :id =>"show" %>
        <% if current_user %>
        <%= link_to 'Edit', edit_post_path(post) %>
        <%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?', :id =>"del" } %>
        <% end %>
        <hr class="border" />
      </li>
    <% end -%>
   </ul>
  <br>
  <%= will_paginate @posts, :class => "page", renderer: BootstrapPagination::Rails%>
  </div>
  </div>
 </div>

</div>

app/views/posts/new.html.erb
<% provide(:title, "New-Post") %>
<%= render 'nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>


<div class="new-post">
	<div class="container">
	  <div class="row">
	    <div class="col-sm-12 col-md-12 col-lg-9 col-sm-9">
	    	<h1>New Post</h1>

			<%= render 'form', post: @post %>

			<%= link_to 'Back', posts_path %>
	    </div>
		
	   </div>
	</div>
</div>

app/views/posts/show.html.erb
<% provide(:title, "Post") %>
<%= render 'nav' %>
<script type="text/javascript">
  $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    })
</script>
<div class="post-show">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-xs-12 col-md-9 col-lg-9">
              <div class="para">
				
				<p id="notice"><%= notice %></p>
                <% if @post.image? %>
				<%= image_tag @post.image.url %>
				<% end -%> 
				<h5>
  					<span class="fa fa-clock-o" aria-hidden="true"></span><strong><%= @post.date %>
					</strong>
				</h5>

				<h3>
  					<strong><%= @post.title.capitalize %></strong>
				</h3>

				<p>
  					<%= kramdown @post.content %>
				</p>				
                <% if current_user %>
				<%= link_to 'Edit', edit_post_path(@post) %> |
				<% end %>
				<%= link_to 'Back', posts_path %>
				<hr/>
					<u><h4><strong>Comments</strong></h4></u>
				<% if @post.comments.any? %>
					<%= render @post.comments %>
				<% else %>
                    <p> NO commnets yet</p>
                <% end -%>
				<u><h5><strong>Add a comment:</strong></h5></u>
				<%= render 'comments/form' %>
				
             </div>
			</div>
		</div>
	</div>
</div>

app/views/welcome/index.html.erb
<% provide(:title, "Home") %>
<section class="home" id="home"  data-anchor="home">
	<div class="container-fluid">
		<div class="row">
			<div class="col-xs-12 col-sm-12">

			   
				<%= image_tag('/assets/karai.png') %>
				<hr class="line"/>
				<p>
					KaraiGLUG is a community orgainsation located in karaikudi, affiliated to
					<a href="http://fsftn.org">FSFTN</a> 
				</p>
     		</div>
		</div>
	</div>

    <div class="nav hidden-sm hidden-xs">
	   <ul class="menu">
		   <li>
          <a href="#home" class="active">Home</a>
		      <a href="#aug">About-us</a>
          <a  href="#gallery">Gallery</a>
		      <a href="#contact">Contact-us</a>
          <%= link_to 'Blog', posts_path %>
       </li>
	   </ul>
    </div>


    <div class="navi hidden-md hidden-lg">
      <div id="mySidenav" class="sidenav">
        <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
        <a href="#home">Home</a>
        <%= link_to 'Blog', posts_path %>
        <a href="#events">Events</a>
        <a href="#aug">community project</a>
        <a href="#contact">Contact-us</a>
      </div>

      <div id="main">
        <span style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776; </span>
      </div>
  </div>
</div>
</section>



<script>
function openNav() {
    document.getElementById("mySidenav").style.width = "250px";
    document.getElementById("main").style.marginLeft = "250px";
}

function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
    document.getElementById("main").style.marginLeft= "0";
}
$('#mySidenav a').on('click',function(){
  document.getElementById("mySidenav").style.width = "0";
  document.getElementById("main").style.marginLeft= "0";
})  
</script>

<!-- Home page end -->

<section class="events" id="events">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-xs-12">
                <h3>Our Recent Events </h3>
                <hr class="line" / >
                <ul class="e-list">
                	   <a href="#">
                	    <li>
                	     <h5><span class="fa fa-calendar-o " aria-hidden="true"></span>
                          AUG 11-15 2k17</h5>
                	     <h4>Showcase Our Dream Project LDL</h4>
                	     <br/><br/><br/><br/>
                	     <hr class="hr" />
                         <p>Karai-glug Events</p>
                       </li>   
                       </a>
                	   <a href="#">
                	    <li>
                	     <h5><span class="fa fa-calendar-o" aria-hidden="true"></span>Aug 30 2k17</h5>
                	     <h4>LDL Inauguration In Govt.school</h4>
                	     <br/><br/><br/><br/>
                	     <hr class="hr" />
                         <p>Karai-glug Events</p>
                	    </li>
                	  </a>
                </ul>
			</div>
		</div>
	</div>
</section>
<!-- Events end -->

<section class="aug" id="aug">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-xs-12 ">
				<h3>About-us</h3>
				<hr class="line"/>
				<p>
					KaraiGLUG or Karaikudi GNU/Linux Users Group located in Karaikudi, Tamil nadu, is part of <a href="http://fsftn.org">FSFTN</a>. Its an initiative to propogate the ideology of free software and to popularize the usage of the free software and open hardware. Since 2015, KaraiGLUG has conducted many workshops,talks and seminors in colleges and schools in Karaikudi,Pudukottai,Trichy, etc. KaraiGLUG is also associated with socially useful projects such as Project Bodhi, Libre Digital Library and have digitized many Libraries in Karaikudi for free of cost.
				</p>
				<a href="/assets/ldl.png" data-gall="gall-frame" data-type="ajax"> <%= image_tag("/assets/ldl.png",  :class => "img") %>
               </a>			   
		</div>
	</div>
   </div>
</section>

<div class="aug30">
	<div class="container-fluid">
		<div class="row">
			<div class="col-sm-12 col-xs-12 ">
				<h3>LDL Installation in govr.school</h3>
				<hr class="line"/>
				<p>
			   <span>Dear all,Greetings..</span><br/> we are happy to inform that, the <span>inaugural function of Libre Digital Library in Ramanathan Chettiar Municipal High School</span> will be held on tomorrow (30.08.2017). For this event, the Principal of RMHS invited District Chief Educational Officer (CEO). He will open the LDL setup and Smart Class room. The smart class room already linked with LDL. We hope that, this event may help us to deploy LDL in Govt Schools at large scale.  Join with us for this great event.

			  <br/><br/>
            </p>
            <a href="/assets/back.jpg">
             <%= image_tag('/assets/back.jpg') %>
            </a>
    		</div>
	  </div>
   </div>
</div>


<div class="gallery" id="gallery">
  <div class="container">  
  <div class="row">
  	<div class="col-sm-12 col-xs-12">
  		 <h4>Photo Gallery</h4>
    <hr class="line" />
    <p>Some captured moments from event.</p>   
      <div class="images"> 
        <a href="/assets/4.jpg">
    		<%= image_tag("/assets/4.jpg") %>
    	</a>
        
    	<a href="/assets/6.jpg">
    		<%= image_tag("/assets/6.jpg") %>
    	</a>
    	<a href="/assets/7.jpg">
    		<%= image_tag("/assets/7.jpg") %>
    	</a>
    	<a href="/assets/8.jpg">
    		<%= image_tag("/assets/8.jpg") %>
    	</a>
    	<a href="/assets/back.jpg">
    		<%= image_tag("/assets/back.jpg") %>
    	</a>
    	<a href="/assets/16.jpg">
    		<%= image_tag("/assets/16.jpg") %>
    	</a>
    	<a href="/assets/12.jpg">
    		<%= image_tag("/assets/12.jpg") %>
    	</a>
    	<a href="/assets/15.jpg">
    		<%= image_tag("/assets/15.jpg") %>
    	</a>

     </div>
 </div>
</div>
<div class="see-more">
  <%= link_to 'See-more-photos', gallery_index_path %>
</div>
</div>
</div>

   
<section class="contact" id="contact">
	<div class="container">
		<div class="row">
			<div class="col-xs-12 col-sm-12">
				<ul class="footer-fonts">
					<li><a href="https://www.facebook.com/karaiglug/"><i class="fa fa-facebook" aria-hidden="true"></i>
					</a></li>
						<li><a href="https://gitlab.com/karaiGLUG"><i class="fa fa-gitlab" aria-hidden="true"></i>
					</a></li>
						<li><a href="mailto:karaiglug@gmail.com"><i class="fa fa-envelope-o" aria-hidden="true"></i>
					</a></li>
				</ul>
				<ul class="copyright">
						<li><span> KARAIGLUG. All wrongs reserved</span>.<a href="http://copyleft.org/" target="_blank">Copyleft</a></li>
						<li><span>Icons: </span> <a href="http://fontawesome.io/">Font awesome</a></li>
						<li><span>Images: </span> <a href="http://unsplah.com">Unsplash</a></li>
					</ul>
			</div>
		</div>
	</div>
</section>

  <script type="text/javascript">
  
    $('.menu').scrollToFixed({marginTop:0});       
    $('nav button').on('click',function(){
       $('#myNavbar').toggle();
    });
    $('.mob-nav a span').on('click',function(e){
       e.preventDefault();
       $('.mob-menu').toggle();
    });
    $(document).ready(function(){
      $(document).on("scroll", onScroll);
      $('a[href^="#"]').on('click', function (e) {
        e.preventDefault();
        $(document).off("scroll");
        
        $('a').each(function () {
            $(this).removeClass('active');
        })
        $(this).addClass('active');
      
        var target = this.hash,
            menu = target;
        $target = $(target);
        $('html, body').stop().animate({
            'scrollTop': $target.offset().top+2
        }, 500, 'swing', function () {
            window.location.hash = target;
            $(document).on("scroll", onScroll);
        });
    });
});
function onScroll(event){
    var scrollPos = $(document).scrollTop();
    $('.menu a').each(function () {
        var currLink = $(this);
        var refElement = $(currLink.attr("href"));
        if (refElement.position().top <= scrollPos && refElement.position().top + refElement.height() > scrollPos) {
            $('.nav ul li a').removeClass("active");
            currLink.addClass("active");
        }
        else{
            currLink.removeClass("active");
        }
    });
}
  </script>